<?php
/**
 * Copyright © 2015 Alexander Lukjanenko (alexander.lukjanenko@gmail.com)
 */

$title = 'Payouts';
$this->headTitle($title);
?>

    <div class="jumbotron">
        <h1><?php echo sprintf($this->translate('%s%s%s'), $title, '<span class="zf-green">', '</span>') ?></h1>
    </div>

    <h2>Period: <?php echo $payouts->getPeriodText(); ?> </h2>
    <h3>Gross sales: <?php echo sprintf('%.2f', $payouts->getEarnings()); ?> </h3>
    <h3>Total (payouts): <?php echo sprintf('%.2f', $payouts->getTotal()); ?> </h3>
    <h3>Income: <?php echo sprintf('%.2f', ($payouts->getEarnings() - $payouts->getTotal())); ?> </h3>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php if (isset($payouts)) : ?>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Salary</th>
                                <th>Prepaid</th>
                                <th>Sales</th>
                                <th>Extended Support</th>
                                <th>Total</th>
                                <th>Skrill</th>
                                <th>Details</th>
<!--                                <th>Actions</th>-->
                            </tr>
                            </thead>
                            <?php $i = 1; ?>
                            <?php foreach($payouts->getPayouts() as $payout): ?>
                                <tbody>
                                <tr>
                                    <td><?php echo $i; ?></td>
                                    <td><?php echo $payout->getDeveloper()->getName(); ?></td>
                                    <td><?php echo sprintf('%.2f',$payout->getFixedMoney()); ?></td>
                                    <td><?php echo sprintf('%.2f',$payout->getPrepaidMoney()); ?></td>
                                    <td><?php echo sprintf('%.2f',$payout->getDefaultSales()); ?>
                                    <td><?php echo sprintf('%.2f',$payout->getExtendedSupportSales()); ?>
                                       <?php //echo sprintf('%.2f',$payout->getDefaultSales()); ?>
                                       <?php //echo sprintf('%.2f',$payout->getExtendedSupportSales()); ?></td>
                                    <td><?php echo sprintf('%.2f',$payout->getTotal()); ?></td>
                                    <td><?php echo $payout->getDeveloper()->getSkrill(); ?></td>
                                    <td>
                                        <!-- Button trigger modal -->
                                        <button type="button" class="btn btn-primary showmodal" data-target="#myModal" data-id="<?php echo $i; ?>">
                                            View Details
                                        </button>
                                        <div style="display: none;" id="payout<?php echo $i; ?>">
<?php echo $payout->getDetails(); ?>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                                <?php $i++; ?>
                            <?php endforeach; ?>
                        </table>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php if (isset($payouts)) : ?>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Transaction</th>
                            <th>Skrill</th>
                            <th>Description</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $earnings = $payouts->getEarningsPerAccount(); ?>
                        <tr>
                            <td><?php echo sprintf('%.2f', ($earnings[0]['balance'] )); ?></td>
                            <td>Account #1 <?php echo $payouts->getPeriodText(); ?></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><?php echo sprintf('%.2f', ($earnings[1]['balance'] )); ?></td>
                            <td>Account #2 <?php echo $payouts->getPeriodText(); ?></td>
                            <td></td>
                        </tr>

                        <?php foreach($payouts->getPayouts() as $payout): ?>
                        <tr>
                            <td><?php echo "-" . sprintf('%.2f',$payout->getTotal()); ?></td>
                            <td><?php echo $payout->getDeveloper()->getSkrill(); ?></td>
                            <td><?php echo $payout->getDeveloper()->getName(); ?></td>
                        </tr>
                        <?php endforeach; ?>

                        </tbody>
                    </table>
                    <?php endif; ?>
                </div>
            </div>
            <br>
            <br>
            <br>
            <a href="<?php echo $this->url('developer', array('action'=>'savepayout', 'id' => $periodid));?>" class="btn btn-danger">Save Payouts</a>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Details</h4>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(function(){
            $('.showmodal').click(function(ev){
                ev.preventDefault();
                var uid = $(this).data('id');
                var details = $(('#payout'+uid)).html();
                $('#myModal .modal-body').html(details);
                $('#myModal').modal('show');
//                $.get('test-modal.php?id=' + uid, function(html){
//                    $('#modal-7 .modal-body').html(html);
//                    $('#modal-7').modal('show', {backdrop: 'static'});
//                });
            });
        });
    </script>

<?php


?>