<?php
$title = 'Edit Partner for - ' . $partner->getDeveloper()->getName() . ' ('.$partner->getItem()->getName().')';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<form method="post" class="form">
    <div class="form-group">
        <label for="percent">%</label>
        <input type="text" class="form-control" id="percent" name="percent" placeholder="10" value="<?php echo $partner->getShare(); ?>">
        <label for="percent">% extended support</label>
        <input type="text" class="form-control" id="support" name="support" placeholder="50" value="<?php echo $partner->getSupportShare(); ?>">
        <input type="hidden" name="partner" id="partner" value="<?php echo $partner->getId(); ?>">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>