<?php
$title = 'Import statements';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if (isset($message)) : ?>
    <div class="alert alert-danger" role="alert"><?php echo $message; ?></div>
<?php endif; ?>

<form enctype="multipart/form-data" action="/file/upload" method="POST">
    <div class="form-group">
        <input type="hidden" name="MAX_FILE_SIZE" value="1000000" />
        <label for="statement">CSV file</label>
        <input type="file" class="form-control" id="statement" name="statement">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>