<?php
/**
 * Copyright © 2015 Alexander Lukjanenko (alexander.lukjanenko@gmail.com)
 */
?>
<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Import log'), '<span class="zf-green">', '</span>') ?></h1>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">

                <?php echo $message; ?>

            </div>
        </div>
    </div>
</div>