<?php
/**
 * Copyright © 2015 Alexander Lukjanenko (alexander.lukjanenko@gmail.com)
 */

$title = 'Performance';
$this->headTitle($title);
?>

    <div class="jumbotron">
        <h1><?php echo sprintf($this->translate('%s%s%s'), $title, '<span class="zf-green">', '</span>') ?></h1>
    </div>

    <h2>Period: <?php echo $period['start_date']->format('Y-m-d H:i:s') . " - " . $period['stop_date']->format('Y-m-d H:i:s'); ?> </h2>

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php if (isset($items)) : ?>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Amount</th>
                            </tr>
                            </thead>
                            <?php $i = 1; ?>
                            <?php foreach($items as $item): ?>
                                <tbody>
                                <tr>
                                    <td><?php echo $i; ?></td>
                                    <td><?php echo $item['name']; ?></td>
                                    <td><?php echo $item['sales']; ?></td>
                                </tr>
                                </tbody>
                                <?php $i++; ?>
                            <?php endforeach; ?>
                        </table>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>